socket:
  port: 8899

oracle:
  username: FLO
  password: flo
  schemas: FLO
  instance: orcl
  directory_name: DATA_PUMP_DIR
  dirertory_path: D:\app\dayandnightcycle\admin\orcl\dpdump\

  win: cmd /c start
